### ISSUE TITLE
Add a bitcoin address for small donations

### ISSUE THREAD

**Issue by jonathancross** [libresmartphone/libresmartphone#2]
The README encourages donations, but there is no actual way for users to donate.
I suggest adding a bitcoin address to the readme and the website.

**Comment by libresmartphone** [comment]
For the moment I will use a bank account if that can help people! I think that is better to avoid paypal and since the Mt. Gox incident I don't know if bitcoin is secure.

**Comment by jonathancross** [comment]
> since the Mt. Gox incident I don't know if bitcoin is secure.

Bitcoin and the the bitcoin network are very secure.
MtGox was just a poorly-developed website designed to trade **_Magic: the Gathering_** cards. Don't let the MtGox collapse fool you into thinking there is an issue with the actual security of Bitcoin (a decentralized, permissionless, cryptographically secure network for value transfer)  :-)
