### ISSUE TITLE
Add contact / discussion nfo

### ISSUE THREAD

**Issue by jonathancross** [libresmartphone/libresmartphone#4]
The README suggests that users provide feedback, but it is unclear how you would like this.
* Should they email you?
* Create an issue here on GitHub?
* Is there a mailing list they should use?

**Comment by libresmartphone** [comment]
This is a very important issue that even with the email or creating an issue in Github I think is unresolved.

I thought of making a phpBB forum for other people interested in making open hardware smartphones to contribute their own thoughts.
 
What do you (jonathan) is the best method a forum / mailing list / other?

**Comment by jonathancross** [comment]
I think creating your own PHP forum is a lot of work and probably inferior to many free options out there.

Unfortunately I'm new to all of this, so I can't recommend anything specific. I did do a little googling and came up with this: 

1. I'd suggest for now that we just have people submit issues here in GitHub for items specific to libresmartphone.

2. For general discussions on open hardware phones, there is probably already forums that can be used.  Could create a thread on the _Open Source Hard Ware Association_ (OSHWA) site: http://community.oshwa.org
    They also have a mailing list: http://lists.oshwa.org/listinfo/discuss
    Might make sense to team up with [Replicant](http://www.replicant.us/) community?
    The [Open Pheonux project](http://openphoenux.org/) has the [TinkerPhones mailing list](http://lists.goldelico.com/mailman/listinfo/community).

3. If you really want to have  your own discussion platform, you might consider [Slack](https://slack.com). It works similar to IRC, but is much more rich & user friendly.  [Mattermost](https://about.mattermost.com/) is an Open Source version of Slack.

Hope that helps.

**Comment by jonathancross** [comment]
Just noticed that there is a discussion area here as well which might be good enough for now:
https://hackaday.io/project/6310-libresmartphone
